version: '3'
services:
  ckan:
    container_name: ckan
    build: ./ckan
    links:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    environment:
      - CKAN_SITE_URL=http://localhost:5000
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis
    depends_on:
      - redis
      - solr
      - mongodb
      - db
  db:
    container_name: db
    image: ckan/postgresql:latest
  solr:
    container_name: solr
    build: ./solr
    ports:
      - "8983:8983"
  redis:
    container_name: redis
    image: redis:latest
  mongodb:
    container_name: mongo
    image: bitnami/mongodb:latest
    ports:
        - "27017:27017"
    environment:
        - MONGODB_ROOT_PASSWORD=mongo
        - MONGODB_USERNAME=ckan
        - MONGODB_PASSWORD=ckan
        - MONGODB_DATABASE=ckan
networks:
    default:
        external:
             name: ldap_ldap
