version: '3'

services:
  ldap:
    container_name: ldap
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    command: [--copy-service,  --loglevel, debug]
    volumes:
      - ./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/data.ldif
    environment:
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_BASE_DN=dc=example,dc=org
    networks:
      - ldap
  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    links:
      - ldap
    depends_on:
      - ldap
    networks:
      - ldap
    #
networks:
  ldap:
    # use the bridge driver, but enable IPv6
    driver: bridge
